
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Pittsburgh Cultural Trust 🐧
* Environment: Production
* Id: 0b696280-83e0-00a0-1a8d-d2963b6c0462
* 
* -------------------------------------------------------------------------------
**/

/**
 * All taxonomy codename values for Blog Type
 *
 * Codename: blog_type
 * Id: 6747d3b1-f4ba-49e0-b395-3465d89cd59d
 */
export const blogTypeValues = [
  "cultural_celebration",
  "history",
  "benedum",
  "icon_awards",
  "gala",
  "accessibility_in_action",
] as const;

/**
 * Type representing Blog Type taxonomy
 *
 * Codename: blog_type
 * Id: 6747d3b1-f4ba-49e0-b395-3465d89cd59d
 */
export type BlogType = (typeof blogTypeValues)[number];

/**
 * Type guard for Blog Type
 *
 * Codename: blog_type
 * Id: 6747d3b1-f4ba-49e0-b395-3465d89cd59d
 */
export function isBlogType(value: string | undefined | null): value is BlogType {
  return typeof value === "string" && (blogTypeValues as readonly string[]).includes(value);
}
