
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Pittsburgh Cultural Trust 🐧
* Environment: Production
* Id: 0b696280-83e0-00a0-1a8d-d2963b6c0462
* 
* -------------------------------------------------------------------------------
**/

/**
 * All taxonomy codename values for Event Type
 *
 * Codename: event_type
 * Id: 7af235fc-b9f5-476b-a383-9e3eaa494bd9
 */
export const eventTypeValues = [
  "free",
  "talks___poetry",
  "visual_arts",
  "workshops___classes",
  "ballet___dance",
  "broadway___musical_theater",
  "live_music",
  "opera",
  "film",
  "family",
  "classical",
  "comedy",
  "concert",
] as const;

/**
 * Type representing Event Type taxonomy
 *
 * Codename: event_type
 * Id: 7af235fc-b9f5-476b-a383-9e3eaa494bd9
 */
export type EventType = (typeof eventTypeValues)[number];

/**
 * Type guard for Event Type
 *
 * Codename: event_type
 * Id: 7af235fc-b9f5-476b-a383-9e3eaa494bd9
 */
export function isEventType(value: string | undefined | null): value is EventType {
  return typeof value === "string" && (eventTypeValues as readonly string[]).includes(value);
}
