
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Pittsburgh Cultural Trust 🐧
* Environment: Production
* Id: 0b696280-83e0-00a0-1a8d-d2963b6c0462
* 
* -------------------------------------------------------------------------------
**/

/**
 * All taxonomy codename values for Location
 *
 * Codename: location
 * Id: ac41c42a-9522-40a8-a20e-2eda3e0429c8
 */
export const locationValues = [
  "wood_street_galleries",
  "space_gallery",
  "n707_penn_gallery",
  "n820_liberty_gallery",
  "public_art",
  "upcoming_events",
] as const;

/**
 * Type representing Location taxonomy
 *
 * Codename: location
 * Id: ac41c42a-9522-40a8-a20e-2eda3e0429c8
 */
export type Location = (typeof locationValues)[number];

/**
 * Type guard for Location
 *
 * Codename: location
 * Id: ac41c42a-9522-40a8-a20e-2eda3e0429c8
 */
export function isLocation(value: string | undefined | null): value is Location {
  return typeof value === "string" && (locationValues as readonly string[]).includes(value);
}
