
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Pittsburgh Cultural Trust 🐧
* Environment: Production
* Id: 0b696280-83e0-00a0-1a8d-d2963b6c0462
* 
* -------------------------------------------------------------------------------
**/

/**
 * All taxonomy codename values for Organization
 *
 * Codename: organization
 * Id: e50a61d7-4c0b-4ee4-980c-bb29bd5acd0a
 */
export const organizationValues = [
  "august_wilson_african_american_cultural_center",
  "pittsburgh_ballet_theatre",
  "pittsburgh_clo",
  "pittsburgh_cultural_trust",
  "pittsburgh_opera",
  "pittsburgh_public_theater",
  "pittsburgh_symphony_orchestra",
] as const;

/**
 * Type representing Organization taxonomy
 *
 * Codename: organization
 * Id: e50a61d7-4c0b-4ee4-980c-bb29bd5acd0a
 */
export type Organization = (typeof organizationValues)[number];

/**
 * Type guard for Organization
 *
 * Codename: organization
 * Id: e50a61d7-4c0b-4ee4-980c-bb29bd5acd0a
 */
export function isOrganization(value: string | undefined | null): value is Organization {
  return typeof value === "string" && (organizationValues as readonly string[]).includes(value);
}
