
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Pittsburgh Cultural Trust 🐧
* Environment: Production
* Id: 0b696280-83e0-00a0-1a8d-d2963b6c0462
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { BlogType } from "../taxonomies/index.ts";
import type { CoreContentType } from "../system/index.ts";
import type { Metadata } from "../content-type-snippets/index.ts";
import type { Person } from "./index.ts";

/**
 * ✍🏼 Blog Post
 *
 * Id: 336302c0-0634-4974-b33b-8c7b0469e837
 * Codename: blog_post
 */
export type BlogPost = CoreContentType<
  BlogPostElementCodenames,
  {
    /**
     * Title
     *
     * Type: text
     * Required: true
     * Codename: title
     * Id: 72869e6e-2822-4e81-944a-d90b3148ce4a
     */
    readonly title: Elements.TextElement;
    /**
     * Image
     *
     * Type: asset
     * Required: true
     * Codename: image
     * Id: 1361b589-f40e-4c4a-b219-62a0f3f5a8c0
     */
    readonly image: Elements.AssetsElement;
    /**
     * Body
     *
     * Type: rich_text
     * Required: true
     * Codename: body
     * Id: e74bc043-0613-4554-8fb5-4d03a42c61a5
     */
    readonly body: Elements.RichTextElement<CoreContentType>;
    /**
     * Blog Type
     *
     * Type: taxonomy
     * Required: false
     * Codename: blog_type
     * Id: 9b65e14e-4efc-4818-ae1f-9ef341e0795d
     */
    readonly blog_type: Elements.TaxonomyElement<BlogType, "blog_type">;
    /**
     * Author
     *
     * Type: modular_content
     * Required: false
     * Codename: author
     * Id: 58ba0a81-41bc-4212-880b-216f311a03fd
     */
    readonly author: Elements.LinkedItemsElement<Person>;
    /**
     * Photo Credits
     *
     * Type: modular_content
     * Required: false
     * Codename: photo_credits
     * Id: dd328157-3082-46ba-a8aa-5020002ecce1
     */
    readonly photo_credits: Elements.LinkedItemsElement<Person>;
    /**
     * URL slug
     *
     * Type: url_slug
     * Required: true
     * Codename: url_slug
     * Id: cfdddb6d-ae75-431b-ac02-af463468d86b
     */
    readonly url_slug: Elements.UrlSlugElement;
  } & Metadata,
  "blog_post"
>;

/**
 * Type representing all available element codenames for ✍🏼 Blog Post
 */
export type BlogPostElementCodenames =
  | "title"
  | "image"
  | "body"
  | "blog_type"
  | "author"
  | "photo_credits"
  | "metadata__title"
  | "metadata__keywords"
  | "metadata__description"
  | "url_slug";

/**
 * Type guard for ✍🏼 Blog Post
 *
 * Id: 336302c0-0634-4974-b33b-8c7b0469e837
 * Codename: blog_post
 */
export function isBlogPost(item: CoreContentType | undefined | null): item is BlogPost {
  return item?.system?.type === "blog_post";
}
