
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Pittsburgh Cultural Trust 🐧
* Environment: Production
* Id: 0b696280-83e0-00a0-1a8d-d2963b6c0462
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { CoreContentType } from "../system/index.ts";
import type { Page } from "./index.ts";

/**
 * PSO CTA
 *
 * Id: 4d91ac1e-9a6a-4171-8f2c-e21a81b5ef5e
 * Codename: call_to_action__copy_
 */
export type PSOCTA = CoreContentType<
  PSOCTAElementCodenames,
  {
    /**
     * Headline
     *
     * Type: text
     * Required: true
     * Codename: headline
     * Id: 497e4eb5-d1cc-46a3-80ab-75f0d9744f42
     */
    readonly headline: Elements.TextElement;
    /**
     * Subheadline
     *
     * Type: text
     * Required: true
     * Codename: subheadline
     * Id: 380d9f04-a401-45e3-9a7e-f8191e035d32
     */
    readonly subheadline: Elements.TextElement;
    /**
     * Image
     *
     * Type: asset
     * Required: true
     * Codename: image
     * Id: 52d7ca2b-4bca-40e7-93c1-03e842082ab4
     */
    readonly image: Elements.AssetsElement;
    /**
     * Button Label
     *
     * Type: text
     * Required: true
     * Codename: button_label
     * Id: 920106eb-31e7-4ca0-8e2d-a9d03039c815
     */
    readonly button_label: Elements.TextElement;
    /**
     * Button Link
     *
     * Type: modular_content
     * Required: false
     * Codename: button_link
     * Id: b197adf6-5c99-4516-a366-49981add112d
     */
    readonly button_link: Elements.LinkedItemsElement<Page>;
  },
  "call_to_action__copy_"
>;

/**
 * Type representing all available element codenames for PSO CTA
 */
export type PSOCTAElementCodenames = "headline" | "subheadline" | "image" | "button_label" | "button_link";

/**
 * Type guard for PSO CTA
 *
 * Id: 4d91ac1e-9a6a-4171-8f2c-e21a81b5ef5e
 * Codename: call_to_action__copy_
 */
export function isPSOCTA(item: CoreContentType | undefined | null): item is PSOCTA {
  return item?.system?.type === "call_to_action__copy_";
}
