
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Pittsburgh Cultural Trust 🐧
* Environment: Production
* Id: 0b696280-83e0-00a0-1a8d-d2963b6c0462
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { CoreContentType } from "../system/index.ts";
import type { EventType, TaxonomyLocation } from "../taxonomies/index.ts";
import type { ContentLocation as Location, Performance, Person, Sponsor } from "./index.ts";
import type { Metadata } from "../content-type-snippets/index.ts";

/**
 * 🎫 Event
 *
 * Id: e97907ba-c5ae-53e6-bcb6-091bc89da3fa
 * Codename: event
 */
export type Event = CoreContentType<
  EventElementCodenames,
  {
    /**
     * Name
     *
     * Type: text
     * Required: true
     * Codename: name
     * Id: 60502ad7-d552-5435-af46-6f4df84c3ddd
     */
    readonly name: Elements.TextElement;
    /**
     * Image
     *
     * Type: asset
     * Required: true
     * Codename: image
     * Id: b13e797e-0e50-5ecb-aebc-05aa9e180864
     */
    readonly image: Elements.AssetsElement;
    /**
     * Start Date
     *
     * Type: date_time
     * Required: true
     * Codename: start_date
     * Id: 114ba02d-f9dd-5555-a78d-6798d1a835a0
     */
    readonly start_date: Elements.DateTimeElement;
    /**
     * End Date
     *
     * Type: date_time
     * Required: true
     * Codename: end_date
     * Id: a00fecf1-c7ff-5bed-8c40-2eba7460170a
     */
    readonly end_date: Elements.DateTimeElement;
    /**
     * Description
     *
     * Type: rich_text
     * Required: true
     * Codename: description
     * Id: 2a7a8e84-274c-5339-afd2-4865b643fbb2
     */
    readonly description: Elements.RichTextElement<CoreContentType>;
    /**
     * Location
     *
     * Type: modular_content
     * Required: false
     * Codename: location
     * Id: 0a0d4313-d720-4071-b5a3-9e43041111c5
     */
    readonly location: Elements.LinkedItemsElement<Location>;
    /**
     * Accessibility
     *
     * Type: multiple_choice
     * Required: false
     * Codename: accessibility
     * Id: be8e8ab6-309a-43bb-8c7a-a2831e0edbe6
     */
    readonly accessibility: Elements.MultipleChoiceElement<"large_print" | "wheelchair_seating" | "sensory_friendly">;
    /**
     * Event Type
     *
     * Type: taxonomy
     * Required: false
     * Codename: event_type
     * Id: 038955c0-436a-4eb6-90d2-a7eccdc26a70
     */
    readonly event_type: Elements.TaxonomyElement<EventType, "event_type">;
    /**
     * Location
     *
     * Type: taxonomy
     * Required: false
     * Codename: location_tag
     * Id: 90d61383-320d-4d52-8664-93777ea68b02
     */
    readonly location_tag: Elements.TaxonomyElement<TaxonomyLocation, "location_tag">;
    /**
     * Performances
     *
     * Type: modular_content
     * Required: false
     * Codename: performances
     * Id: b82a4764-da71-46fb-bd50-42be00278af5
     */
    readonly performances: Elements.LinkedItemsElement<Performance>;
    /**
     * Performer
     *
     * Type: modular_content
     * Required: false
     * Codename: performer
     * Id: f9434ea6-8bcb-4754-9b0a-6cbb38fee6da
     */
    readonly performer: Elements.LinkedItemsElement<Person>;
    /**
     * URL Slug
     *
     * Type: url_slug
     * Required: true
     * Codename: url_slug
     * Id: 8bc84f2b-d81d-441f-b28f-d35d260ee63e
     */
    readonly url_slug: Elements.UrlSlugElement;
    /**
     * Program
     *
     * Type: text
     * Required: false
     * Codename: program
     * Id: b7cdc877-4aca-4a93-b13d-8f9df7933c84
     * Guidelines: Please write the Composer in all caps, and then the piece after. COMPOSER: Piece
     */
    readonly program: Elements.TextElement;
    /**
     * Sponsors
     *
     * Type: modular_content
     * Required: false
     * Codename: sponsors
     * Id: e06114bf-f5cc-4c67-9f0e-2b63652095e3
     */
    readonly sponsors: Elements.LinkedItemsElement<Sponsor>;
  } & Metadata,
  "event"
>;

/**
 * Type representing all available element codenames for 🎫 Event
 */
export type EventElementCodenames =
  | "name"
  | "image"
  | "start_date"
  | "end_date"
  | "description"
  | "location"
  | "accessibility"
  | "event_type"
  | "location_tag"
  | "performances"
  | "performer"
  | "metadata__title"
  | "metadata__keywords"
  | "metadata__description"
  | "url_slug"
  | "program"
  | "sponsors";

/**
 * Type guard for 🎫 Event
 *
 * Id: e97907ba-c5ae-53e6-bcb6-091bc89da3fa
 * Codename: event
 */
export function isEvent(item: CoreContentType | undefined | null): item is Event {
  return item?.system?.type === "event";
}
