
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Pittsburgh Cultural Trust 🐧
* Environment: Production
* Id: 0b696280-83e0-00a0-1a8d-d2963b6c0462
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { CoreContentType } from "../system/index.ts";
import type { Page } from "./index.ts";

/**
 * Hero Button
 *
 * Id: 7060665b-10a0-4ba1-b3bf-0529a18d1993
 * Codename: hero_button
 */
export type HeroButton = CoreContentType<
  HeroButtonElementCodenames,
  {
    /**
     * Button Text
     *
     * Type: text
     * Required: false
     * Codename: button_text
     * Id: be5d52ed-b1c9-43f6-b236-588ffce1cbf1
     */
    readonly button_text: Elements.TextElement;
    /**
     * Page
     *
     * Type: modular_content
     * Required: false
     * Codename: page
     * Id: f035e355-a071-4b85-8b38-5ced04e77cae
     */
    readonly page: Elements.LinkedItemsElement<Page>;
  },
  "hero_button"
>;

/**
 * Type representing all available element codenames for Hero Button
 */
export type HeroButtonElementCodenames = "button_text" | "page";

/**
 * Type guard for Hero Button
 *
 * Id: 7060665b-10a0-4ba1-b3bf-0529a18d1993
 * Codename: hero_button
 */
export function isHeroButton(item: CoreContentType | undefined | null): item is HeroButton {
  return item?.system?.type === "hero_button";
}
