
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Pittsburgh Cultural Trust 🐧
* Environment: Production
* Id: 0b696280-83e0-00a0-1a8d-d2963b6c0462
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { CoreContentType } from "../system/index.ts";
import type { Event, Video, Disclaimer, CallToAction, PSOCTA, Article, Page } from "./index.ts";

/**
 * PSO Landing Page
 *
 * Id: e5695146-fd72-47fe-967b-732d81cecc2e
 * Codename: landing_page__copy_
 */
export type PSOLandingPage = CoreContentType<
  PSOLandingPageElementCodenames,
  {
    /**
     * Featured Events in Hero
     *
     * Type: modular_content
     * Required: false
     * Codename: featured_events_in_hero
     * Id: a08dc965-0e79-4fe0-b4d4-e1de7f0a512c
     */
    readonly featured_events_in_hero: Elements.LinkedItemsElement<Event>;
    /**
     * Body Copy
     *
     * Type: rich_text
     * Required: false
     * Codename: body_copy
     * Id: c34b91fd-8768-4765-be17-da3799ed4707
     */
    readonly body_copy: Elements.RichTextElement<Video | Disclaimer | CallToAction | PSOCTA>;
    /**
     * Featured Content
     *
     * Type: modular_content
     * Required: false
     * Codename: featured_content
     * Id: d170a3c6-a55f-450a-b049-01f4c7ed946a
     */
    readonly featured_content: Elements.LinkedItemsElement<Event | Article | CallToAction>;
    /**
     * Subpages
     *
     * Type: subpages
     * Required: false
     * Codename: subpages
     * Id: 81621e38-29bc-4a00-a673-038793bc2567
     */
    readonly subpages: Elements.LinkedItemsElement<Page>;
  },
  "landing_page__copy_"
>;

/**
 * Type representing all available element codenames for PSO Landing Page
 */
export type PSOLandingPageElementCodenames = "featured_events_in_hero" | "body_copy" | "featured_content" | "subpages";

/**
 * Type guard for PSO Landing Page
 *
 * Id: e5695146-fd72-47fe-967b-732d81cecc2e
 * Codename: landing_page__copy_
 */
export function isPSOLandingPage(item: CoreContentType | undefined | null): item is PSOLandingPage {
  return item?.system?.type === "landing_page__copy_";
}
