
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Pittsburgh Cultural Trust 🐧
* Environment: Production
* Id: 0b696280-83e0-00a0-1a8d-d2963b6c0462
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { CoreContentType } from "../system/index.ts";
import type { HeroButton, Video, Disclaimer, CallToAction, Event, Article, Page } from "./index.ts";

/**
 * Landing Page
 *
 * Id: cc5060fc-1b09-40b6-a07f-5eb885301747
 * Codename: landing_page
 */
export type LandingPage = CoreContentType<
  LandingPageElementCodenames,
  {
    /**
     * Headline
     *
     * Type: text
     * Required: true
     * Codename: headline
     * Id: 19b37bc8-cd8a-43a2-a647-61732524abed
     */
    readonly headline: Elements.TextElement;
    /**
     * Subheadline
     *
     * Type: text
     * Required: true
     * Codename: subheadline
     * Id: 1f3be25d-1bcf-4e59-9003-14490f82f338
     */
    readonly subheadline: Elements.TextElement;
    /**
     * Hero Buttons
     *
     * Type: modular_content
     * Required: false
     * Codename: hero_links
     * Id: bb9a36b5-865f-4d75-a66b-d2e0e2ca09fe
     */
    readonly hero_links: Elements.LinkedItemsElement<HeroButton>;
    /**
     * Hero Image
     *
     * Type: asset
     * Required: true
     * Codename: hero_image
     * Id: 5030bc21-47d3-451f-b5e7-d59d8d7a2439
     */
    readonly hero_image: Elements.AssetsElement;
    /**
     * Body Copy
     *
     * Type: rich_text
     * Required: false
     * Codename: body_copy
     * Id: 7b9826ff-5cb0-450f-b16a-bd176aed04cf
     */
    readonly body_copy: Elements.RichTextElement<Video | Disclaimer | CallToAction>;
    /**
     * Featured Content
     *
     * Type: modular_content
     * Required: false
     * Codename: featured_content
     * Id: 38cf004b-3054-43ff-9b7a-f0734b1d35f1
     */
    readonly featured_content: Elements.LinkedItemsElement<Event | Article | CallToAction>;
    /**
     * Subpages
     *
     * Type: subpages
     * Required: false
     * Codename: subpages
     * Id: 9d5080db-f2bb-41a1-bcbe-11786ee3a59d
     */
    readonly subpages: Elements.LinkedItemsElement<Page>;
  },
  "landing_page"
>;

/**
 * Type representing all available element codenames for Landing Page
 */
export type LandingPageElementCodenames =
  | "headline"
  | "subheadline"
  | "hero_links"
  | "hero_image"
  | "body_copy"
  | "featured_content"
  | "subpages";

/**
 * Type guard for Landing Page
 *
 * Id: cc5060fc-1b09-40b6-a07f-5eb885301747
 * Codename: landing_page
 */
export function isLandingPage(item: CoreContentType | undefined | null): item is LandingPage {
  return item?.system?.type === "landing_page";
}
