
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Pittsburgh Cultural Trust 🐧
* Environment: Production
* Id: 0b696280-83e0-00a0-1a8d-d2963b6c0462
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { CoreContentType } from "../system/index.ts";

/**
 * 🏢 Location
 *
 * Id: e820b7d6-3ff3-47a6-89e4-8d3c57bc9d03
 * Codename: location
 */
export type Location = CoreContentType<
  LocationElementCodenames,
  {
    /**
     * Name
     *
     * Type: text
     * Required: true
     * Codename: name
     * Id: 3632944e-a340-4c43-b398-543e122e06ef
     */
    readonly name: Elements.TextElement;
    /**
     * Street Address
     *
     * Type: text
     * Required: true
     * Codename: street_address
     * Id: 7acb1b46-3f36-4593-b0a3-316d49acad41
     */
    readonly street_address: Elements.TextElement;
    /**
     * City
     *
     * Type: text
     * Required: true
     * Codename: city
     * Id: 73e442f3-be17-4379-b798-10cb323b200f
     */
    readonly city: Elements.TextElement;
    /**
     * State
     *
     * Type: text
     * Required: true
     * Codename: state
     * Id: c5be31fc-f4ee-42b9-b4d5-0bf33fd5ac3b
     * Guidelines: Use the abbreviation for the state (i.e. PA for Pennsylvania)
     */
    readonly state: Elements.TextElement;
    /**
     * Zipcode
     *
     * Type: text
     * Required: true
     * Codename: zipcode
     * Id: 9ecef29c-da9c-475c-baab-4482f88bee0f
     */
    readonly zipcode: Elements.TextElement;
  },
  "location"
>;

/**
 * Type representing all available element codenames for 🏢 Location
 */
export type LocationElementCodenames = "name" | "street_address" | "city" | "state" | "zipcode";

/**
 * Type guard for 🏢 Location
 *
 * Id: e820b7d6-3ff3-47a6-89e4-8d3c57bc9d03
 * Codename: location
 */
export function isLocation(item: CoreContentType | undefined | null): item is Location {
  return item?.system?.type === "location";
}
