
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Pittsburgh Cultural Trust 🐧
* Environment: Production
* Id: 0b696280-83e0-00a0-1a8d-d2963b6c0462
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { CoreContentType } from "../system/index.ts";
import type { Event } from "./index.ts";

/**
 * 🎟️ Performance
 *
 * Id: 6e02dc3c-755b-4544-acf1-cc7aea636604
 * Codename: _performance
 */
export type Performance = CoreContentType<
  PerformanceElementCodenames,
  {
    /**
     * Event
     *
     * Type: modular_content
     * Required: true
     * Codename: event
     * Id: 4ae46c92-7eb1-410a-b457-d5a22a79c664
     */
    readonly event: Elements.LinkedItemsElement<Event>;
    /**
     * Time and Date
     *
     * Type: date_time
     * Required: false
     * Codename: time_and_date
     * Id: 4aaddffd-aba4-468a-8b34-c6f465c60558
     */
    readonly time_and_date: Elements.DateTimeElement;
  },
  "_performance"
>;

/**
 * Type representing all available element codenames for 🎟️ Performance
 */
export type PerformanceElementCodenames = "event" | "time_and_date";

/**
 * Type guard for 🎟️ Performance
 *
 * Id: 6e02dc3c-755b-4544-acf1-cc7aea636604
 * Codename: _performance
 */
export function isPerformance(item: CoreContentType | undefined | null): item is Performance {
  return item?.system?.type === "_performance";
}
