
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Pittsburgh Cultural Trust 🐧
* Environment: Production
* Id: 0b696280-83e0-00a0-1a8d-d2963b6c0462
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { CoreContentType } from "../system/index.ts";

/**
 * Series
 *
 * Id: 636175dc-5085-469d-be61-877ce4a540c2
 * Codename: series
 */
export type Series = CoreContentType<
  SeriesElementCodenames,
  {
    /**
     * Title
     *
     * Type: text
     * Required: false
     * Codename: title
     * Id: 0c0f50ce-21fa-4594-a33d-d3ba5575c13a
     */
    readonly title: Elements.TextElement;
    /**
     * Body
     *
     * Type: rich_text
     * Required: false
     * Codename: body
     * Id: 197089cd-2389-4c86-afc3-a8a33b0fb235
     */
    readonly body: Elements.RichTextElement<CoreContentType>;
    /**
     * Events
     *
     * Type: modular_content
     * Required: false
     * Codename: events
     * Id: 73796bd1-7bfc-474f-9a71-a876685e434d
     */
    readonly events: Elements.LinkedItemsElement<CoreContentType>;
    /**
     * Image
     *
     * Type: asset
     * Required: false
     * Codename: image
     * Id: 17cdbc7d-a326-484f-a135-4b5031ecdef7
     */
    readonly image: Elements.AssetsElement;
  },
  "series"
>;

/**
 * Type representing all available element codenames for Series
 */
export type SeriesElementCodenames = "title" | "body" | "events" | "image";

/**
 * Type guard for Series
 *
 * Id: 636175dc-5085-469d-be61-877ce4a540c2
 * Codename: series
 */
export function isSeries(item: CoreContentType | undefined | null): item is Series {
  return item?.system?.type === "series";
}
