
/** 
* This file has been auto-generated by '@kontent-ai/model-generator@8.0.0'.
* 
* (c) Kontent.ai
*  
* -------------------------------------------------------------------------------
* 
* Project: Pittsburgh Cultural Trust 🐧
* Environment: Production
* Id: 0b696280-83e0-00a0-1a8d-d2963b6c0462
* 
* -------------------------------------------------------------------------------
**/

import type { Elements } from "@kontent-ai/delivery-sdk";
import type { CoreContentType } from "../system/index.ts";

/**
 * Sponsor
 *
 * Id: ec60cc3b-864a-43c7-9996-60a8ffd53d11
 * Codename: sponsor
 */
export type Sponsor = CoreContentType<
  SponsorElementCodenames,
  {
    /**
     * Sponsor Logo
     *
     * Type: asset
     * Required: false
     * Codename: sponsor_logo
     * Id: 5a02bdea-29f1-456b-9364-f3d3cd457147
     */
    readonly sponsor_logo: Elements.AssetsElement;
    /**
     * Body
     *
     * Type: text
     * Required: false
     * Codename: body
     * Id: 7e38f04a-f4f8-49ba-b263-3b41ec6ada51
     */
    readonly body: Elements.TextElement;
  },
  "sponsor"
>;

/**
 * Type representing all available element codenames for Sponsor
 */
export type SponsorElementCodenames = "sponsor_logo" | "body";

/**
 * Type guard for Sponsor
 *
 * Id: ec60cc3b-864a-43c7-9996-60a8ffd53d11
 * Codename: sponsor
 */
export function isSponsor(item: CoreContentType | undefined | null): item is Sponsor {
  return item?.system?.type === "sponsor";
}
